### ISSUE TITLE
Does "Independant" mean decoupled from facebook's libraries and tech

### ISSUE THREAD

**Issue by mooror** [f/graphql.js#14]
After the recent licensing issues with Facebook's BSD + Patents license the company I work for is very hesitant to use any of their libraries. However we still wish to make use of the GraphQL standard as it seems to be the way of the future. So my question is, does "independent" mean that this repository has no dependencies on Facebook libraries?

**Comment by f** [comment]
It means "agnostic" but yes, it does not depend any Facebook library.
