### ISSUE TITLE
It seems the "http.js" and "https.js" and "url.js" is needed?

### ISSUE THREAD

**Issue by chaim1986** [f/graphql.js#16]
It seems the "http.js" and "https.js" abd "url.js" is needed?  where can i find these js files?

--- graphql.js ----
  
xhr.send(body)
      } else if (typeof require == 'function') {
        var http = require('http'), https = require('https'), URL = require('url'), uri = URL.parse(url);
        var req = (uri.protocol === 'https:' ? https : http).request({
          protocol: uri.protocol,
          hostname: uri.hostname,

**Comment by f** [comment]
They are built-in Node libraries to use with Node.

**Comment by chaim1986** [comment]
I got it.. Thanks a ton. ^^
