### ISSUE TITLE
.then is not a function

### ISSUE THREAD

**Issue by diit** [f/graphql.js#2]
## Context
```
var graphql = require('graphql.js')

var graph = graphql('someurl, {
  headers: {
    'Authorization': `Bearer XXX`,
    'Content-Type': 'application/json'
  }
}

function getX() {
  return graph('query me { name }')
}

getX().then(me => {
  console.log(me)
})
```

All bundled with webpack, errors on .then call and add the `graph.query('...')` does not seem to affect a change.

## Expected Result
- Console logs data

## Actual Result
- Error on .then
- No network requests made

**Comment by f** [comment]
`graph()` returns a function that accepts variables as parameter. You need
to use direct execution. `graph.run()` or `graph.query.run()`

> --

*Fatih Kadir Akın*http://github.com/f
http://twitter.com/fkadev

**Comment by f** [comment]
```js
getX()(/* variables here as object */).then(me => { console.log(me) })
```

is also valid.

16 Şub 2017 Per 22:40 tarihinde Fatih Kadir Akın <fatihkadirakin@gmail.com>
şunu yazdı:

> `graph()` returns a function that accepts variables as parameter. You need
> to use direct execution. `graph.run()` or `graph.query.run()`
>
> --
>
> *Fatih Kadir Akın*http://github.com/f
> http://twitter.com/fkadev
>
-- 

*Fatih Kadir Akın*http://github.com/f
http://twitter.com/fkadev

**Comment by diit** [comment]
That worked!

**Comment by bwyss** [comment]
I am having issues resolving the promise, but the above solution does not help. Can you provide a working example? 

The documentation on the README shows:

```
graph(`query ($email: String!, $password: String!) {
  auth(email: $email, password: $password) {
    ... auth # if you use any fragment, it will be added to the query.
    ... error
  }
}`, {
  email: "john@doe.com",
  password: "my-super-password"
}).then(function (response) {
  // response is originally response.data of query result
  console.log(response)
}).catch(function (error) {
  // response is originally response.errors of query result
  console.log(error)
})
```

I am not able to get this to console log the response.
