### ISSUE TITLE
Query is returning data in debugger, but .then() is never called

### ISSUE THREAD

**Issue by flewellyn** [f/graphql.js#24]
I'm successfully sending the GraphQL queries to my server, the data is returning, Chrome debugger shows the response data in the network view, but my invocation of .then() never gets called.  My function that I pass in to call console.log does not run, and the promise always shows as "pending" even after the call returns.

What could be the issue?

**Comment by f** [comment]
May you create an example on JSFiddle or alike that behaves similar and I
can check out.

**Comment by flewellyn** [comment]
I can paste the code here:

`gq = graphql("http://localhost:9999/query");

wb = gq(
	'query { worldBorders { gid, name } }');
wb().then(function (r) { console.log(r); }).catch(function (e) { console.log(e); });`

That's basically it.  Chrome's DevTools show that the data is being returned.  A sample:
`{"worldBorders":[{"gid":"1","name":"Antigua and Barbuda"},{"gid":"2","name":"Algeria"}...]}`

It's all there.  But then() is never called.

**Comment by flewellyn** [comment]
I decided to try and debug the library myself.  I'd been using the minified version, and so I grabbed the non-minified version instead.  Lo and behold, trying it out before I even modified it to add debugging statements, it worked.

So, whatever's wrong is wrong with graphql.min.js, and not with graphql.js.

**Comment by flewellyn** [comment]
I suppose we could close this issue, if there's nothing more to say about it?
