### ISSUE TITLE
.mutate() does not autodeclare variables

### ISSUE THREAD

**Issue by flewellyn** [f/graphql.js#27]
When I use the .query() helper method with autodeclare, it works perfectly.  However, .mutate() does not autodeclare the variables for input.

I can still use the main function and enter the full mutation syntax, with manual declarations.  But having the helper method work properly would be nice.

**Comment by f** [comment]
Yes, mutate cannot autodeclare input.

You should use `field!Type` syntax to help autodeclaration.

```js
    graph.mutate(gql`(@autodeclare) {
      userCreate(input: $input) {
        user {
          ...userInfo
        }
      }
    }`, { 'input!UserCreateInput': { name: "Fatih", surname: "Akin" } });
```

**Comment by flewellyn** [comment]
Ahh, I see.  Yes, this works nicely. Thank you.
